### ISSUE TITLE
ça m'intéresse, tu peux m'en dire plus ? 

### ISSUE THREAD

**Issue by nbckk9** [acamilleri/tgvmaxhelper#3]
Que faisait ton programme ? Pourquoi trainline t'a contacté pour que tu fermes le projet ?

**Comment by acamilleri** [comment]
Salut, mon programme avait une interface afin de réserver automatiquement des trajets. Un cron tournait toutes les X minutes pour vérifier si le trajet était disponible et si c'était le cas le voyage était automatiquement réservé. 
J'utilisais l'API front de Trainline et ça ne respecte pas leur CGV, donc j'ai reçu des menaces de la part d'un dev, notamment de rapporter les faits à la SNCF et de blacklist les cartes tgvmax utilisés par le projet.
